### PR TITLE
Changes to make.bat

### PR DESCRIPTION
**Pull request by double-beep**
Remove lines add start /min /wait. @Counterply, there are also some "start" commands in the make.bat that have only "start /min" and not "start /min /wait". Should I correct them?

### CODE REVIEW

**Comment by double-beep** [comment]
Hi @Counterply, can you review and say me if my changes are correct?

**Comment by CounterPly** [comment]
Hi double-beep,

I left those lines as launching an assembly process to the immediate console intentionally, as this is very useful for debugging purposes. Furthermore, if someone explicitly chooses bmi2 or popcnt, chances are they just want one executable so it doesn't make sense to execute assembly in a separate terminal. The `start /min` instructions are to simply start the assembly process on different threads so that many executables can be made concurrently, and the `/wait` flag compensates for bottlenecks. This saves several minutes worth of time during bulk-assembly operations by taking advantage of a CPU's multiple threads. 

I appreciate you taking the time to look at this though. I noticed some small spelling mistakes, etc that you flagged, so I'll make a note to fix those in my next commit. 

Also, I'm taking a short break from asmFish. In part, because I am feeling a little burnt-out from the March patches, but I also have a few work-related matters to attend to. I won't be gone too long and should hopefully be back in mid-June to pick up where I left off (assuming Moha or Lyudmil don't continue patching in the meantime). 

Best,

Justin

**Comment by double-beep** [comment]
@Counterply, of course I am taking the time to look though. I can close this pull request and open a new soon. Now, I think that `start /min` should only be placed in allBinaries, correct? What about the lines and the executable(s)? Should they remain?
Have a nice break! :! AND CLOSING THE PULL REQUEST!

**Comment by double-beep** [comment]
I am deleting this branch and make a new one.

**Comment by double-beep** [comment]
And I fresh pull request of course!

**Pull request closed without merging**
