### PR TITLE
Pawn endgames directly skip early pruning

### PR DESCRIPTION
**Pull request by CounterPly**
Original patch: 
https://github.com/official-stockfish/Stockfish/commit/d19348221395a5939603bbd1364fda60e4ffd2ee

Bench: 5466219

### CODE REVIEW

**Comment by lantonov** [comment]
@Counterply 
Thanks for the patch. I will commit shortly after testing the behaviour of the executables (benches, assembled in windows? linux?, equal game pairs?).

**Comment by CounterPly** [comment]
Thanks. I remember you mentioning that you are usually between countries around this time, so whenever is convenient for you would be great.

**Comment by lantonov** [comment]
Yes, it's the same situation this time too. I saw that this is a subsequent change which makes it more valuable. Thank you for this. This is the last change before the big one: the introduction of contempt which should bring about 20 Elo.
I shall try to spare some more time for perusal of the OTM restoration comparing 3 sources: Aug 14, Aug 16, and Feb 19 '18.

**Comment by lantonov** [comment]
Bench
asmFishW = asmFishL = stockfish-d193482 (Pawn endgames directly skip early pruning) = 5466219
Score of stockfish-d193482 vs asmFishW_2018-02-19_bmi2.exe: 196 - 196 - 608 [0.500] 1000 depth 14
Elo difference: 0.00 +/- 13.47
SPRT: llr 8.88e-15, lbound -2.94, ubound 2.94
0/500 different
[results.txt](https://github.com/lantonov/asmFish/files/1738413/results.txt)

**Comment by CounterPly** [comment]
I noticed you may have merged my master branch by mistake. Sorry for this confusion. 

One easy fix would be to run:
`git reset --hard HEAD~1
`
Until the last commit from your master is restored. Then pull and merge from: 
https://github.com/Counterply/asmFish/tree/pawnEndgames

This branch should be identical to your last master with the exception of the latest Pawn Endgames patch.

**Comment by lantonov** [comment]
I wanted to combine this with a formatting commit of mine but it became too complicated. Have to delete several merges from master

**Comment by lantonov** [comment]
Ok, now I cleaned the master and it contains only the latest patch

**Pull request merged**
