### PR TITLE
update to 22 Jan

### PR DESCRIPTION
**Pull request by tthsqe12**
I found only one error in a previous commit. Signed division by powers by powers of 2 is not so simple.

### CODE REVIEW

**Comment by CounterPly** [comment]
Thanks for these patches, Moha. Two more patches until "asmFish 9."

____

**Benches:**

asmFishW_2018-04-08_bmi2
bench
*** bench hash 16 threads 1 depth 13 ***
1:      nodes: 302447           2240 knps       135 ms
2:      nodes: 230326           2531 knps       91 ms
3:      nodes: 140475           4256 knps       33 ms
4:      nodes: 117578           3014 knps       39 ms
5:      nodes: 87627            2738 knps       32 ms
6:      nodes: 133396           2615 knps       51 ms
7:      nodes: 247051           2714 knps       91 ms
8:      nodes: 513477           3093 knps       166 ms
9:      nodes: 244105           2773 knps       88 ms
10:     nodes: 128767           3388 knps       38 ms
11:     nodes: 229763           2497 knps       92 ms
12:     nodes: 187663           2606 knps       72 ms
13:     nodes: 191834           2906 knps       66 ms
14:     nodes: 91781            2781 knps       33 ms
15:     nodes: 101440           3497 knps       29 ms
16:     nodes: 78083            3394 knps       23 ms
17:     nodes: 55232            4248 knps       13 ms
18:     nodes: 22575            4515 knps       5 ms
19:     nodes: 71727            4482 knps       16 ms
20:     nodes: 162176           4504 knps       36 ms
21:     nodes: 84946            4719 knps       18 ms
22:     nodes: 42641            7106 knps       6 ms
23:     nodes: 116513           5296 knps       22 ms
24:     nodes: 36407            4045 knps       9 ms
25:     nodes: 14362            3590 knps       4 ms
26:     nodes: 55219            3944 knps       14 ms
27:     nodes: 504126           3706 knps       136 ms
28:     nodes: 187246           3671 knps       51 ms
29:     nodes: 96141            3697 knps       26 ms
30:     nodes: 26885            4480 knps       6 ms
31:     nodes: 76417            5878 knps       13 ms
32:     nodes: 86324            5395 knps       16 ms
33:     nodes: 63052            6305 knps       10 ms
34:     nodes: 89673            4719 knps       19 ms
35:     nodes: 136468           4402 knps       31 ms
36:     nodes: 150537           6021 knps       25 ms
37:     nodes: 449655           4202 knps       107 ms
38:     nodes: 5724             5724 knps       1 ms
39:     nodes: 40076            3082 knps       13 ms
40:     nodes: 0                0 knps          1 ms
41:     nodes: 0                0 knps          0 ms
42:     nodes: 183409           2547 knps       72 ms
\===========================
Total time (ms) : 1749
Nodes searched  : 5783344
Nodes/second    : 3306657

____

armFishL_2018-04-08_v8
bench
*** bench hash 16 threads 1 depth 13 ***
1:      nodes: 302447           458 knps
2:      nodes: 230326           527 knps
3:      nodes: 140475           672 knps
4:      nodes: 117578           485 knps
5:      nodes: 87627            458 knps
6:      nodes: 133396           450 knps
7:      nodes: 247051           484 knps
8:      nodes: 513477           518 knps
9:      nodes: 244105           453 knps
10:     nodes: 128767           508 knps
11:     nodes: 229763           455 knps
12:     nodes: 187663           429 knps
13:     nodes: 191834           490 knps
14:     nodes: 91781            465 knps
15:     nodes: 101440           522 knps
16:     nodes: 78083            534 knps
17:     nodes: 55232            587 knps
18:     nodes: 22575            594 knps
19:     nodes: 71727            664 knps
20:     nodes: 162176           667 knps
21:     nodes: 84946            668 knps
22:     nodes: 42641            870 knps
23:     nodes: 116513           882 knps
24:     nodes: 36407            606 knps
25:     nodes: 14362            512 knps
26:     nodes: 55219            552 knps
27:     nodes: 504126           490 knps
28:     nodes: 187246           490 knps
29:     nodes: 96141            549 knps
30:     nodes: 26885            597 knps
31:     nodes: 76417            812 knps
32:     nodes: 86324            763 knps
33:     nodes: 63052            741 knps
34:     nodes: 89673            711 knps
35:     nodes: 136468           685 knps
36:     nodes: 150537           840 knps
37:     nodes: 449655           651 knps
38:     nodes: 5724             440 knps
39:     nodes: 40076            417 knps
40:     nodes: 0                0 knps
41:     nodes: 0                0 knps
42:     nodes: 183409           414 knps
\===========================
Total time (ms) : 10849
Nodes searched  : 5783344
Nodes/second    : 533076

**Comment by lantonov** [comment]
The second of these patches -- Retire lever -- will be easy for me because it doesn't require new code.

**Comment by tthsqe12** [comment]
I will do a couple more. It is faster if I can do a bunch at a time. Also, removing code is not always easy.

**Comment by lantonov** [comment]
Score of asmFishW_2018-04-07_bmi2 vs stockfish-254d995: 23 - 23 - 54  [0.500] 100 games depth=14
Elo difference: 0.00 +/- 46.39
SPRT: llr 2.94e-15, lbound -2.94, ubound 2.94
0/50 differing pairs

Build Tester: 1.4.7.0
Windows 10 (Version 10.0, Build 0, 64-bit Edition)
Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
SafeMode: No 
Running In VM: No 
HyperThreading Enabled: No 
CPU Warmup: Yes
Command Line: bench 256 4 18 default depth
Tests per Build: 30
ANOVA: n/a

                Engine# (NPS)             Speedup     Sp     Conf. 99.5%  S.S.
`1  (5,401,486.5   ) --->       2  (4,631,477.6   ) --->   16.626%      202,662.9    Yes       No `

**Comment by ghost** [comment]
Thanks guys - updates very much appreciated !

**Comment by lantonov** [comment]
After the Contempt 20 patch, the default contempt stays = 0. Should it be so?

**Comment by tthsqe12** [comment]
Ah, I will fix that in a more robust way soon. It is just a cosmetic error.

**Comment by lantonov** [comment]
@tthsqe12 What do you think of making dynamic contempt a little different than SF like this:
```c++
              alpha = std::max(rootMoves[PVIdx].previousScore - delta,-VALUE_INFINITE);
               beta  = std::min(rootMoves[PVIdx].previousScore + delta, VALUE_INFINITE);
 
-              ct =  Options["Contempt"] * PawnValueEg / 100; // From centipawns
+              int ctb =  Options["Contempt"]; // base contempt
+              ct = ctb * PawnValueEg / 100; // From centipawns
 
               // Adjust contempt based on current bestValue (dynamic contempt)
-              ct += int(std::round(48 * atan(float(bestValue) / 128)));
+              ct += int(std::round(4 * ctb * atan(float(bestValue) / 128)));
 
               Eval::Contempt = (us == WHITE ?  make_score(ct, ct / 2)
                                             : -make_score(ct, ct / 2));
```
The idea is when we make Contempt = 0 in options, all contempt to be switched off. Default contempt is 12 in this version. This is to make some analysis people happy because they think that evaluation with contempt makes analysis worse.

**Comment by MichaelB7** [comment]
I support your suggestion fully!!

**Comment by tthsqe12** [comment]
What is the precision on that arctan? Is this in official too?
BWT, I coincidentally just implemented an arctangent function in https://github.com/tthsqe12/cas/blob/master/mpfloat.cpp#L1673

**Comment by lantonov** [comment]
The arctan exists in the official SF introduced with this patch https://github.com/official-stockfish/Stockfish/commit/82697f1193cc8c99c99c282361a3ada25c758243
The new are the lines
```c++
              int ctb =  Options["Contempt"]; // base contempt
              ct = ctb * PawnValueEg / 100; // From centipawns
```
which define a variable that would zero the dynamic contempt (the arctan expression) when option Contempt is set to 0.

**Comment by tthsqe12** [comment]
Why would they use such an expensive function as arctan?
x/(1+|x|) looks just like arctan(x) to me.

**Comment by lantonov** [comment]
Before this patch dynamic contempt was logarithmic. Arctan was introduced by Ivan Ivec. I prefer to withhold my opinion about his patches.
You are perfectly right about x/(1+|x|). It deserves to be tested in Fishtest as a replacement of arctan.
I submitted the patch http://tests.stockfishchess.org/tests/view/5aca49ba0ebc5934e80f75a1

**Pull request merged**
