### PR TITLE
Two more patches and an update for the fasmg assembly engine

### PR DESCRIPTION
**Pull request by CounterPly**
This patch should have been trivial, but strangely, I cannot seem to get the benches to align. I suspect this is something similar to the issue reported in https://github.com/lantonov/asmFish/pull/141 whereby a skipped non-functional patch was ultimately responsible for the bench misalignment.

Or perhaps I am just overlooking something obvious here.

In either case, feedback would be very appreciated, as I am running out of ideas.

Current Bench:    4985524
Target Bench:    5170165

Original patch:
https://github.com/official-stockfish/Stockfish/commit/b88374b14a7baa2f8e4c37b16a2e653e7472adcc

### CODE REVIEW

**Comment by CounterPly** [comment]
I figured it out. The mistake was at line 1443. I think Moha meant to jump to .18fail_high (not .MovePickDone). It didn't actually change the bench until now because we jump to .MovePickDone anyway after the assert. 

In any case, I will fix this and commit the result shortly.

**Comment by Ipmanchess** [comment]
Nice work you do!
Have here asmFish 2018-06-12 in testing..and it starts very well..

**Comment by double-beep** [comment]
@Counterply, you are amazing!
Q: Is flatassembler i5y0r faster?
I will open a pr for the executables soon.

**Comment by CounterPly** [comment]
Thanks, @double-beep . 

re: fasmg i5y0r
It is slightly faster, but not by much. I save roughly 0.3 seconds per build on average with this version.

**Comment by double-beep** [comment]
I don't save time. I earn time! This is later than g.i4pue!

**Pull request merged**
