### PR TITLE
Seven patches and new BMI1 builds (for AMD processors)

### PR DESCRIPTION
**Pull request by CounterPly**
**Includes:**
- 7 new functional patches for asmFish and armFish
- New bmi1 executables (for AMD users). These executables will help bridge the performance gap between popcnt and bmi2 builds on many modern AMD (popcnt) processors.

### CODE REVIEW

**Comment by double-beep** [comment]
Hi @Counterply,

Benches:

bmi2:
```
*** bench hash 16 threads 1 depth 13 ***
1:      nodes: 137568           1719 knps       80 ms
2:      nodes: 270468           1865 knps       145 ms
3:      nodes: 101436           2817 knps       36 ms
4:      nodes: 141919           1267 knps       112 ms
5:      nodes: 93835            1737 knps       54 ms
6:      nodes: 99702            1749 knps       57 ms
7:      nodes: 108559           1644 knps       66 ms
8:      nodes: 311520           1832 knps       170 ms
9:      nodes: 135774           1697 knps       80 ms
10:     nodes: 64308            2009 knps       32 ms
11:     nodes: 256561           1655 knps       155 ms
12:     nodes: 258910           1681 knps       154 ms
13:     nodes: 166349           1647 knps       101 ms
14:     nodes: 93331            1728 knps       54 ms
15:     nodes: 123644           1962 knps       63 ms
16:     nodes: 45160            2150 knps       21 ms
17:     nodes: 121834           2436 knps       50 ms
18:     nodes: 21483            3069 knps       7 ms
19:     nodes: 63263            2875 knps       22 ms
20:     nodes: 431873           2879 knps       150 ms
21:     nodes: 50793            3386 knps       15 ms
22:     nodes: 29607            4229 knps       7 ms
23:     nodes: 70686            4158 knps       17 ms
24:     nodes: 45350            2667 knps       17 ms
25:     nodes: 10170            2034 knps       5 ms
26:     nodes: 35769            2751 knps       13 ms
27:     nodes: 150071           2308 knps       65 ms
28:     nodes: 198332           2179 knps       91 ms
29:     nodes: 41441            2302 knps       18 ms
30:     nodes: 16332            2722 knps       6 ms
31:     nodes: 60007            3750 knps       16 ms
32:     nodes: 44220            3401 knps       13 ms
33:     nodes: 37948            4216 knps       9 ms
34:     nodes: 71716            3118 knps       23 ms
35:     nodes: 171647           3065 knps       56 ms
36:     nodes: 54533            3408 knps       16 ms
37:     nodes: 368160           2707 knps       136 ms
38:     nodes: 5897             1965 knps       3 ms
39:     nodes: 20682            2068 knps       10 ms
40:     nodes: 0                0 knps          0 ms
41:     nodes: 0                0 knps          1 ms
42:     nodes: 246816           1572 knps       157 ms
===========================
```
Total time (ms) : 2303
Nodes searched  : **4777674 (correct bench)**
Nodes/second    : 2074543

popcnt
```
*** bench hash 16 threads 1 depth 13 ***
1:      nodes: 137568           1698 knps       81 ms
2:      nodes: 270468           1803 knps       150 ms
3:      nodes: 101436           2898 knps       35 ms
4:      nodes: 141919           1892 knps       75 ms
5:      nodes: 93835            1706 knps       55 ms
6:      nodes: 99702            1533 knps       65 ms
7:      nodes: 108559           1620 knps       67 ms
8:      nodes: 311520           1721 knps       181 ms
9:      nodes: 135774           1560 knps       87 ms
10:     nodes: 64308            1891 knps       34 ms
11:     nodes: 256561           1371 knps       187 ms
12:     nodes: 258910           1588 knps       163 ms
13:     nodes: 166349           1663 knps       100 ms
14:     nodes: 93331            1696 knps       55 ms
15:     nodes: 123644           1994 knps       62 ms
16:     nodes: 45160            1806 knps       25 ms
17:     nodes: 121834           2388 knps       51 ms
18:     nodes: 21483            3069 knps       7 ms
19:     nodes: 63263            2875 knps       22 ms
20:     nodes: 431873           2768 knps       156 ms
21:     nodes: 50793            3386 knps       15 ms
22:     nodes: 29607            4934 knps       6 ms
23:     nodes: 70686            4158 knps       17 ms
24:     nodes: 45350            2519 knps       18 ms
25:     nodes: 10170            2034 knps       5 ms
26:     nodes: 35769            2751 knps       13 ms
27:     nodes: 150071           2344 knps       64 ms
28:     nodes: 198332           2132 knps       93 ms
29:     nodes: 41441            2302 knps       18 ms
30:     nodes: 16332            3266 knps       5 ms
31:     nodes: 60007            3000 knps       20 ms
32:     nodes: 44220            3685 knps       12 ms
33:     nodes: 37948            3794 knps       10 ms
34:     nodes: 71716            3259 knps       22 ms
35:     nodes: 171647           2959 knps       58 ms
36:     nodes: 54533            3895 knps       14 ms
37:     nodes: 368160           2648 knps       139 ms
38:     nodes: 5897             1965 knps       3 ms
39:     nodes: 20682            1880 knps       11 ms
40:     nodes: 0                0 knps          0 ms
41:     nodes: 0                0 knps          0 ms
42:     nodes: 246816           1542 knps       160 ms
===========================
```
Total time (ms) : 2361
Nodes searched  : **4777674 (correct bench)**
Nodes/second    : 2023580

base
```
*** bench hash 16 threads 1 depth 13 ***
1:      nodes: 190513           1107 knps       172 ms
2:      nodes: 292859           1683 knps       174 ms
3:      nodes: 113211           2761 knps       41 ms
4:      nodes: 104840           1397 knps       75 ms
5:      nodes: 121919           1543 knps       79 ms
6:      nodes: 102048           1478 knps       69 ms
7:      nodes: 229796           1542 knps       149 ms
8:      nodes: 269909           1719 knps       157 ms
9:      nodes: 180544           1492 knps       121 ms
10:     nodes: 72463            1575 knps       46 ms
11:     nodes: 241641           1579 knps       153 ms
12:     nodes: 258859           1487 knps       174 ms
13:     nodes: 107317           1676 knps       64 ms
14:     nodes: 167857           1539 knps       109 ms
15:     nodes: 152021           1924 knps       79 ms
16:     nodes: 87304            1940 knps       45 ms
17:     nodes: 82709            2432 knps       34 ms
18:     nodes: 16963            2423 knps       7 ms
19:     nodes: 80103            2966 knps       27 ms
20:     nodes: 152804           2634 knps       58 ms
21:     nodes: 41040            3156 knps       13 ms
22:     nodes: 25323            3165 knps       8 ms
23:     nodes: 89416            4064 knps       22 ms
24:     nodes: 40853            1856 knps       22 ms
25:     nodes: 8467             2116 knps       4 ms
26:     nodes: 40505            2025 knps       20 ms
27:     nodes: 237839           2086 knps       114 ms
28:     nodes: 149125           2015 knps       74 ms
29:     nodes: 98530            2141 knps       46 ms
30:     nodes: 32221            2301 knps       14 ms
31:     nodes: 66196            3677 knps       18 ms
32:     nodes: 45494            3499 knps       13 ms
33:     nodes: 38817            3881 knps       10 ms
34:     nodes: 97493            3144 knps       31 ms
35:     nodes: 120255           2796 knps       43 ms
36:     nodes: 178775           3803 knps       47 ms
37:     nodes: 398904           2477 knps       161 ms
38:     nodes: 6100             2033 knps       3 ms
39:     nodes: 22025            1694 knps       13 ms
40:     nodes: 0                0 knps          0 ms
41:     nodes: 0                0 knps          0 ms
42:     nodes: 160864           1436 knps       112 ms
===========================
```
Total time (ms) : 2621
Nodes searched  : **4923922** (Why this?)
Nodes/second    : 1878642

Source: https://ci.appveyor.com/project/Counterply/asmfish-026ic/build/3.0.2

Note: I have also downloaded the executable and gives the same bench. Is there a problem?

**Comment by double-beep** [comment]
Problem with MatefinderW_base.exe also.

**Comment by CounterPly** [comment]
Very strange -- good spot! I'll do a git bisect when I have time to try to isolate the mismatch. If not in the next 24 hours, then I'll do it this weekend for sure (today and tomorrow are quite busy for me).

If you can do the [git-bisect](https://git-scm.com/docs/git-bisect) yourself, that would be extremely helpful, but no worries if you don't feel comfortable doing so.

Good job again finding this.

**Comment by double-beep** [comment]
I am bisecting at the moment. Please as my computer is too slow assembling commit executables after **every** patch. Please...

**Comment by double-beep** [comment]
Git-bisect finished!
```
d1b35ce7a2e98496fb8842ababeb47cb2218e482 is the first bad commit
commit d1b35ce7a2e98496fb8842ababeb47cb2218e482
Author: @Counterply <counterply@gmail.com>
Date:   Fri Jul 6 18:49:47 2018 -0400

Drop the lever condition for backwards bench 4773882

https://github.com/official-stockfish/Stockfish/tree/6634f41ac9e76fe623dd36d312b6955ab2c66a4f

:040000 040000 da4f91ed1233dbf120bf6f539a925e8c0d4fbea9 4c46cafd4966a70f869bf9972d902c2d73996254 M      arm
:040000 040000 b6f0582cc6abdf81b6d659313926ab69ed06ea25 0cefe17a57bfd7ed6fce805160c5fad2813410e9 M      x86
```

**Comment by double-beep** [comment]
Note: I only did:
```
git bisect start
git bisect bad
git bisect good a5285c3
Bisecting: 4 revisions left to test after this (roughly 2 steps)
[7d8f74932c2447cd818d143117ae144086cec956] Tweak null move pruning conditions bench 5088156
git bisect bad
Bisecting: 1 revision left to test after this (roughly 1 step)
[e5a55217b6e6e38c8dbd410ed8b21ecfa4e2f0bc] Remove skipEarlyPruning argument to to search() bench 4953556
git bisect good
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[d1b35ce7a2e98496fb8842ababeb47cb2218e482] Drop the lever condition for backwards bench 4773882
git bisect bad
```
and my comment above.

**Comment by double-beep** [comment]
Bug squashed! https://github.com/lantonov/asmFish/commit/d1b35ce7a2e98496fb8842ababeb47cb2218e482#diff-34fae779a1208b33c2377c7eead1f738L189-L195

**Pull request merged**
