### PR TITLE
Executables

### PR DESCRIPTION
**Pull request by double-beep**
This change is [Reviewable](https://reviewable.io/reviews/lantonov/asmfish/193)

### CODE REVIEW

**Comment by CounterPly** [comment]
Thank you. Your other commit changes look good, by the way. I will double check them once I get there and include you in the PR.

**Comment by double-beep** [comment]
Thanks a lot! What about AppVeyor?

**Comment by CounterPly** [comment]
@double-beep 

I am experimenting with AppVeyor now (it is awesome). I have a few questions though.

1) Is it possible to have the binaries directly integrated into the repository or is it just to test whether or not a build fails? If the former, then it is only really necessary to build asmFish (Windows) and armFish (Android) since the other operating systems just use the same source as asmFish (Windows).

2) I noticed under the test_script section of your appveyor.yml file you only are benching windows. Ideally, it would also be nice to take the bench of armFish as well since it is built from distinct source code. If the objective is to save time, then this would help tremendously if there were a way to accomplish this. Do you know if the VM appveyor uses for builds is capable of running qemu?

3) Could you elaborate why exactly this section of the YAML file is necessary?

`environment:
  nuget_user: doublebeep7@gmail.com
  nuget_password:
    secure: tgMKHKjoECZJvbF81E9C1g==`

**Comment by double-beep** [comment]
1. I think that access is denied to AppVeyor to every repository. It presents only the artifacts in the artifacts tab if I understand well your question. If you want a folder-artifact, it will present you `foldername.zip`. If you want a *.* file you should put quotes like this: '*.*'. Path must be relative to `clone_folder`
2. I tried `armFishL_%datestamp%_v8 bench` but I got `armFishL_%datestamp%_v8 is not recognised as an internal or external command, operable program or batch file.`
3. Delete that. I was experimenting with NuGet packages, but nothing.

I think you know that to export current settings to YAML file go to settings and select `Export YAML`.

**Comment by double-beep** [comment]
Tried again to bench armFish but got the same message as before: `armFishL_... is not recognised as...`

**Comment by double-beep** [comment]
👎

**Comment by CounterPly** [comment]
1. Ok, this makes sense. For repository purposes, I will just continue to assemble the files locally (I do that anyway since I have to constantly check to see if I have the correct bench).

2. You are getting the armFish error because the remote machine does not have qemu (an emulator for numerous architectures, including ARM) installed. I tried remotely installing it, but sadly it requires permissions that I do not have (which makes sense, since malicious users could download a harmful program). I will simply continue to verify the arm benches locally. 

3. Ok, no problem. 

In summary, I will commit a simplified version of your AppVeyor script that builds and tests three specific executables: asmFishW_bmi2, asmFishW_popcnt, asmFishW_base. The reasoning for this is 1) the remote machine can only bench windows executables, and 2) due to the automation that the fasmg assembly engine provides if these three executables work then the others will work too.

Even though AppVeyor can't automatically commit executables to the branch for us, it is still helpful in the sense that it double-checks that a commit didn't break anything. This will save me the trouble of having to bench all executables prior to merging a PR.

**Comment by double-beep** [comment]
Thanks!
Requesting installing qemu to the AppVeyor staff may help. But I really don't understand: Why don't you assemble ALL executables (except ARM of course)?

**Comment by CounterPly** [comment]
Assembling all executables would be pointless on multiple levels.

 1) It does not make sense to assemble all executables since I will have to commit the executables manually anyway (as we've already established, AppVeyor is incapable of doing so). 

2) As I mentioned, the fasmg assembly engine uses the same source to generate Windows+Linux+Mac+MateFinder binaries. The differences between operating system binaries are hard-coded into the source, so this means that if one works, they all will all work. 

3) We couldn't bench the others anyway even if we did make them (which, as I've stated above is redundant) since AppVeyor is only for Windows.

**Comment by double-beep** [comment]
1.  You can simply download the executables from there and publish them in the repository.
2. 

> **hard-coded**..., so this means that **if one works, they all will all work**.

I don't understand the bold...

3. Do you have all of these operating systems to bench ALL the executables? :curious

**Comment by CounterPly** [comment]
It is easier to simply push to my repository since I already have them built. Downloading them first is an extra step that is unnecessary in my workflow.

No, I do not have all of these operating systems. I use qemu for architecture emulation and Hyper-V for OS emulation.

**Comment by CounterPly** [comment]
> I don't understand the bold...

What I wrote should be clear. They are built from the same source, and the part of the source that is responsible for the separate executables does not change. So if one executable works, they all work. 

I would recommend reading more about fasmg if you still don't understand what I mean. 

https://flatassembler.net/docs.php?article=fasmg

**Comment by double-beep** [comment]
> It is easier to simply push to my repository since I already have them built. Downloading them first is an extra step that is unnecessary in my workflow.

Let me explain you: Let AppVeyor build them first. Then, go to the artifacts tab and download the built executables.

> No, I do not have all of these operating systems. I use qemu.

Then, how do you bench executables?

> What I wrote should be clear. They are built from the same source, and the part of the source that is responsible for the separate executables does not change. So if one executable works, they all work.

Where is the problem here?

**Comment by CounterPly** [comment]
1) I understand that. As I've stated, they are already built by the time I get the benches aligned. So why would I download something that I already built? 

2) I bench them with qemu (armFish) and Hyper-V (Mac, Linux).

> Where is the problem here?

3) I am not sure what you mean. What "problem" are you referring to?

**Comment by double-beep** [comment]
Why assembling the executables directly at AppVeyor is pointless because they are built from the same source, and the part of the source that is responsible for the separate executables does not change. So if one executable works, they all work?

**Comment by double-beep** [comment]
Commit in GitHub what you think without the executables. Then, let AppVeyor build the executables and download them. Upload them to your repository and you are ready.

**Comment by CounterPly** [comment]
When I am doing a patch I frequently take benches locally. This is much faster than staging+commiting changes each time, then navigating to AppVeyor to see what the bench was (not to mention, my machine is around 7-10 seconds faster at building than AppVeyor). I also have scripts + macros that I use locally to help speed up this process. By the time I have the benches aligned, the executables are ready with the code changes.

I think AppVeyor is a good double-check in case someone commits the wrong file by accident and breaks something, but it doesn't help in terms of saving time during the coding process itself.

**Comment by double-beep** [comment]
Sorry, the truth is that my computer is too old and builds the executables in double-time. I prefer AppVeyor here.

Is there a way of going to depth 20 with a command for better testing? I have tried a lot of times.

**Pull request merged**
