### PR TITLE
Three more patches

### PR DESCRIPTION
**Pull request by CounterPly**
### Patch 1:
~~The bench of fdb6df0 is **5643520**, which is 7 nodes short.~~ 
@lantonov After giving it some thought, I am planning **not** to include Patch 1 in the next commit since it does not affect the bench of subsequent patches and gets reverted anyway. Feel free to change this, however.

### Patch 2:
The bench of 313b074 is **5765806**, which is correct. Oddly enough, this is true with or without the previous patch. This can be confirmed by excluding [`59d1037`](https://github.com/official-stockfish/Stockfish/commit/59d10374ca647feebf9323b21031e47012572fb6) in SF as done [here](https://github.com/Counterply/Stockfish/commits/master). 

### Patch 3:
The bench of 0852046 is **6361568**, which is correct. This patch is also seemingly unaffected by the presence (or absence) of Patch 1.

### CODE REVIEW

**Comment by CounterPly** [comment]
Added a third patch [official-stockfish/Stockfish@b873086].

@lantonov @tthsqe12 
Patch 2 [313b074] and Patch 3 [0852046] should be good to go. 

I think it should be safe to skip Patch 1 [fdb6df0] since it (1) does not affect the benches of subsequent patches and (2) eventually gets completey reverted anyway. Any thoughts on this would be greatly appreciated.

**Comment by CounterPly** [comment]
Added arm port for Patch 2. 

armFishL_2018-05-09_v8
*** bench hash 16 threads 1 depth 13 ***
1:      nodes: 426249           480 knps
2:      nodes: 274605           538 knps
3:      nodes: 84727            683 knps
4:      nodes: 200489           550 knps
5:      nodes: 179188           480 knps
6:      nodes: 103861           469 knps
7:      nodes: 231361           481 knps
8:      nodes: 473551           526 knps
9:      nodes: 196575           477 knps
10:     nodes: 118251           509 knps
11:     nodes: 188709           492 knps
12:     nodes: 257362           483 knps
13:     nodes: 170137           497 knps
14:     nodes: 152255           480 knps
15:     nodes: 181237           541 knps
16:     nodes: 69072            527 knps
17:     nodes: 78120            640 knps
18:     nodes: 12908            586 knps
19:     nodes: 66256            736 knps
20:     nodes: 244076           713 knps
21:     nodes: 52047            743 knps
22:     nodes: 46077            921 knps
23:     nodes: 120461           941 knps
24:     nodes: 46074            631 knps
25:     nodes: 9839             491 knps
26:     nodes: 67895            634 knps
27:     nodes: 182411           614 knps
28:     nodes: 128263           585 knps
29:     nodes: 103042           566 knps
30:     nodes: 30188            656 knps
31:     nodes: 60992            802 knps
32:     nodes: 50779            769 knps
33:     nodes: 46733            778 knps
34:     nodes: 131909           701 knps
35:     nodes: 206247           718 knps
36:     nodes: 105384           916 knps
37:     nodes: 461521           652 knps
38:     nodes: 6390             456 knps
39:     nodes: 17307            443 knps
40:     nodes: 0                0 knps
41:     nodes: 0                0 knps
42:     nodes: 183258           423 knps
\===========================
Total time (ms) : 10306
Nodes searched  : 5765806
Nodes/second    : 559461

**Comment by CounterPly** [comment]
Added arm port for Patch 3.

armFishL_2018-05-10_v8
*** bench hash 16 threads 1 depth 13 ***
1:      nodes: 426246           477 knps
2:      nodes: 232002           527 knps
3:      nodes: 121959           655 knps
4:      nodes: 221313           521 knps
5:      nodes: 63740            465 knps
6:      nodes: 146826           463 knps
7:      nodes: 246214           455 knps
8:      nodes: 560544           525 knps
9:      nodes: 213287           473 knps
10:     nodes: 86727            513 knps
11:     nodes: 273385           480 knps
12:     nodes: 241547           472 knps
13:     nodes: 190611           497 knps
14:     nodes: 172700           477 knps
15:     nodes: 88621            527 knps
16:     nodes: 50382            508 knps
17:     nodes: 74174            598 knps
18:     nodes: 22632            611 knps
19:     nodes: 59991            697 knps
20:     nodes: 341408           698 knps
21:     nodes: 63050            708 knps
22:     nodes: 48087            907 knps
23:     nodes: 205031           953 knps
24:     nodes: 58776            618 knps
25:     nodes: 10315            491 knps
26:     nodes: 41098            613 knps
27:     nodes: 388253           590 knps
28:     nodes: 279521           570 knps
29:     nodes: 54207            511 knps
30:     nodes: 25437            635 knps
31:     nodes: 55525            804 knps
32:     nodes: 82349            791 knps
33:     nodes: 51246            813 knps
34:     nodes: 100611           657 knps
35:     nodes: 112830           671 knps
36:     nodes: 144181           901 knps
37:     nodes: 546889           646 knps
38:     nodes: 6446             429 knps
39:     nodes: 26219            476 knps
40:     nodes: 0                0 knps
41:     nodes: 0                0 knps
42:     nodes: 227188           432 knps
\===========================
Total time (ms) : 11449
Nodes searched  : 6361568
Nodes/second    : 555643

**Comment by lantonov** [comment]
@Counterply 
Thanks for the continuing support and the patches. I was in a tight deadline at work and that's why I am late to respond. 
About fdb6df0, good decision to not merge as it gets reverted and bench does not correspond.
I shall make tests on the new patches and list them here.

Score of asmFishW_2018-05-11_bmi2 vs stockfish-b873086: 27 - 28 - 45  [0.495] 100, depth=14 + Syzygy
Elo difference: -3.47 +/- 50.79
SPRT: llr -0.0105, lbound -2.94, ubound 2.94
7 8
9 10
53 54
63 64
65 66
81 82
89 90
97 98
99 100
The number of differing pairs is 9
[results.txt](https://github.com/lantonov/asmFish/files/1998877/results.txt)
Score of asmFishW_2018-05-11_bmi2 vs stockfish-b873086: 20 - 19 - 61  [0.505] 100, depth=14 no Syzygy
Elo difference: 3.47 +/- 42.68
SPRT: llr 0.0148, lbound -2.94, ubound 2.94
15 16
35 36
49 50
93 94
The number of differing pairs is 4
[results.txt](https://github.com/lantonov/asmFish/files/1998893/results.txt)
IMO, the difference with no Syzygy is due to non-implementation of https://github.com/official-stockfish/Stockfish/commit/59d10374ca647feebf9323b21031e47012572fb6 (which we agreed not to implement), and the additional difference with Syzygy is due to non-implementation of https://github.com/official-stockfish/Stockfish/commit/fd4d800c9842ee5b6bf99fa6d06707e678eb14fe

**Comment by CounterPly** [comment]
@lantonov 

No worries. That is the situation I am in this week at work, so I haven't had much time to continue with the patches.

Thanks for the tests. Every once in a while, I try something new for the Shelter Storm patch to see if I can get the benches to match, but so far no luck. If I ever do get it working though before we get to the reverts, I'll let you know.

I haven't looked too much in depth at the next patch, but from what I can see, it is overly difficult due to nomenclature mismatch, which is primarily due to skipping this non-functional patch: https://github.com/official-stockfish/Stockfish/commit/d93baae2205c6adc023b474b852af03f139f792a

If you feel up to it, it would definitely be helpful to try to implement that non-functional patch (mainly just renaming, adding, and deleting labels -- the bench doesn't change). This would make the next patch a lot easier and would make future patches in this section less confusing.

**Comment by lantonov** [comment]
Don't bother too much with the bench and diffs coming from Blocked Pawn Storm. I hope that these would get right when we reach the patches that overwrite this code.
I will look into https://github.com/official-stockfish/Stockfish/commit/d93baae2205c6adc023b474b852af03f139f792a and try to implement it if I can.

**Pull request closed without merging**
