### PR TITLE
aggregate update to Attack threats

### PR DESCRIPTION
**Pull request by tthsqe12**
Ronald's PR was of course correct but I did not observe a matching bench with official.
This PR updates both x86 and arm to
https://github.com/official-stockfish/Stockfish/commit/53239d7d3df44208a915fce84a5745101d3a2ea6

Among the other changes are:
- no more book size limit
- new CPU_HAS_TZCNT flag
- fasmg rolled back to last version I have been working with

### CODE REVIEW

**Comment by tthsqe12** [comment]
I think syzygy1's last patch was not completely correct.
There is now also a checker.py for a more thorough test then merely the bench.

**Comment by syzygy1** [comment]
Strange, the default bench matched on my machine. But thanks for reviewing it :)
I'm pretty sure it wasn't optimal.

**Comment by syzygy1** [comment]
Btw, I think your second patch is reducing the number of andn's compared to your own first patch, not mine ;-)
Lyudmil may want to be careful when merging. Perhaps it is better to first revert my patch?

**Comment by tthsqe12** [comment]
No, nothing needs to be reverted. Everything is fine.

**Comment by syzygy1** [comment]
OK. Btw, I just realised I completely misread your comment about fewer andns.

I still think my patch was correct: bench 1024 1 20 correctly gives 87043313. You probably compared with benches from before the PawnSet[] removal (which your patch seems to reintroduce).

**Comment by tthsqe12** [comment]
I just realised that too.

**Comment by tthsqe12** [comment]
Alright, this PR is updated to https://github.com/official-stockfish/Stockfish/commit/a87a1005ad63c8076a79ea3b2648f87fea49cfc5
now. Bench is 5051254.

**Comment by lantonov** [comment]
I merged the patches with the intention to check later each of them for bench and pgn equality. I had not time to do it today as every Sunday I am flying between countries. Now I will check them carefully both @syzygy1 and @tthsqe12, find the differences and discuss them here. If there is something wrong, there is always the possibility to correct it with additional patch.
Great thanks to both of you.

**Comment by syzygy1** [comment]
@lantonov 
I think there are no problems. Current asmFish seems to be correct and with @tthsqe12 's PR it will get even more up to date.

**Comment by lantonov** [comment]
Ok, I will merge this pull request and then start checking from the beginning, patch by patch. I wonder about "Capture Stat Simplification- Bench: 5363761". It seems so easy and straightforward and one of the first variants I tried was exactly the same as yours and @tthsqe12's. Yet, whatever I did, I could not get bench 5363761. Either there is some twist in it which I couldn't grasp or SF commits are out of sequence. I will start from the end.

**Comment by syzygy1** [comment]
It might be difficult to separate the patches into SF commits. If @tthsqe12 's patch applies cleanly and gives the correct node counts, which it probably does, then it may not be necessary to check the intermediate steps.

Your attempt at capture stat simplification was probably ever so slightly different :-)
Or you made a similar mistake as I did when testing the kingRing simplification... running the wrong asmfish to check bench.

**Comment by tthsqe12** [comment]
my asm repo has the patches clearly separated https://github.com/tthsqe12/asm/commit/526dfec5deb62527cedf07551d45910c5191644f

I am still not good enough with GitHub to incorporate those into a PR.

**Comment by lantonov** [comment]
Thanks, Moha. This info will help me.

**Comment by tthsqe12** [comment]
@lantonov, most of your code was correct and I pointed out the mistake in the arm version at the end of https://github.com/lantonov/asmFish/issues/93.

@syzygy1, while I have your attention, could I ask if you know why gdk_window_process_all_updates is depreciated? What other option is there when drawing takes enough time (i.e. during rotating a plot by holding a key down) to place the queued expose event after the repeated key press event?

**Comment by syzygy1** [comment]
@tthsqe12 
I'm afraid my Gtk knowledge is very very limited...

**Comment by tthsqe12** [comment]
What? I thought I read somewhere that you were involved in gnome... . In that case I retract my question

**Comment by syzygy1** [comment]
I think I once submitted a patch that somehow got applied.

**Pull request merged**
