### PR TITLE
Don't consider defending queen as check blocker

### PR DESCRIPTION
**Pull request by CounterPly**
Original patch: https://github.com/official-stockfish/Stockfish/commit/196ae7c38b99e5e885d319b18a3b2538319de939

Bench: 5767699

### CODE REVIEW

**Comment by CounterPly** [comment]
The rcx register was determined as viable to use here because Moha hammers it on Line 569 of the original source shown below:

`mov   rcx, qword[.ei.attackedBy+8*(8*Us+Queen)]`

**Comment by CounterPly** [comment]
The way the code is organized now is also much cleaner, in my opinion, since it does not temporarily hammer PiecesUs and thus does not require a follow-up XOR to reset its contents.

**Comment by lantonov** [comment]
@Counterply 
Thank you very much for this patch. I had a few tries at it and gave up. Your code is much better. I will test it tonight.

**Comment by CounterPly** [comment]
No worries -- this patch was actually deceivingly difficult. It also took me quite a few attempts to get the correct bench.

Next patch on the agenda:
https://github.com/official-stockfish/Stockfish/commit/020dd69a3512d01c7f189b1aea64fa75c7e1b7cd

**Comment by lantonov** [comment]
Bench
asmFishW_2018-03-07_bmi2.exe = asmFishL_2018-03-07_bmi2 = https://github.com/official-stockfish/Stockfish/commit/196ae7c38b99e5e885d319b18a3b2538319de939 = 5767699
Score of asmFishW_2018-03-07_bmi2.exe vs asmFishW_2018-03-01_bmi2.exe: 17 - 13 - 70 [0.520] 100 games 10+0.1
Elo difference: 13.90 +/- 37.35
SPRT: llr 0.0773, lbound -2.94, ubound 2.94
[results.txt](https://github.com/lantonov/asmFish/files/1790706/results.txt)
Score of asmFishW_2018-03-07_bmi2.exe vs stockfish-196ae7c.exe: 191 - 191 - 618 [0.500] 1000 games depth 14
Elo difference: 0.00 +/- 13.30
SPRT: llr -1.24e-14, lbound -2.94, ubound 2.94
0/500 game pairs different
[results.txt](https://github.com/lantonov/asmFish/files/1790976/results.txt)

**Pull request merged**
