### PR TITLE
Simplify other checks [#1334]

### PR DESCRIPTION
**Pull request by CounterPly**
Commit name disambiguation (the next patch will have the same name) and minor formatting clean up. 

Original patch: https://github.com/official-stockfish/Stockfish/commit/020dd69a3512d01c7f189b1aea64fa75c7e1b7cd

Bench: 5149133

### CODE REVIEW

**Comment by lantonov** [comment]
Ok, I will make a new branch and test it locally

**Comment by CounterPly** [comment]
Sounds good. Sorry for the accidental commit to the main branch earlier.

**Comment by CounterPly** [comment]
Also -- feel free to restore formatting changes as needed. I wrote a script to uniformly align all of the operands because I got tired of the various whitespace discrepancies, but I am not sure if all of the changes adhere to official formatting conventions.

**Comment by lantonov** [comment]
I generally adhere to the conventions specified by Moha in https://github.com/lantonov/asmFish/blob/master/CodeConventions.asm
like instructions justified right, registers justified left, 3 spaces between instructions and registers, 8 spaces step, tabs instead of spaces wherever gap >= 8, etc.
Don't worry about formatting, I can take care of it.

**Comment by lantonov** [comment]
Bench
asmFishW_2018-03-12_bmi2.exe = asmFishL_2018-03-12_bmi2 = official-stockfish/Stockfish@020dd69 = 5149133
Score of asmFishW_2018-03-12_bmi2.exe vs stockfish-020dd69.exe: 21 - 22 - 57 [0.495] 100 games 10+0.1
[results.txt](https://github.com/lantonov/asmFish/files/1804033/results.txt)

Score of asmFishW_2018-03-12_bmi2.exe vs stockfish-020dd69.exe: 15 - 15 - 70 [0.500] 100 games depth 14
0/50 game pairs different
[results.txt](https://github.com/lantonov/asmFish/files/1804072/results.txt)

**Pull request merged**
