### PR TITLE
Executables: Alternative formula for dynamic contempt

### PR DESCRIPTION
**Pull request by double-beep**
Now ARM will be alive, so you will have to do double work 👎

### CODE REVIEW

**Comment by double-beep** [comment]
I am also awaiting answer in #174. Thank you!

**Comment by double-beep** [comment]
I have done commits:
official-stockfish/Stockfish@d4cb80b for both x86 and ARM [here](https://github.com/double-beep/asmFish/commits/my-asmFish)
and official-stockfish/Stockfish@fc0a1f3[here](https://github.com/double-beep/asmFish/commits/cardirufish_patches) for x86 only. They were too easy.
Review them and if they are correct, open a pull request for me when you are ready with patches:
official-stockfish/Stockfish@5a7cdad
official-stockfish/Stockfish@12ef8f7
official-stockfish/Stockfish@06e0134
if you add them, of course.

**Comment by CounterPly** [comment]
Thanks. I'll look into travis as well when I have time.

**Comment by double-beep** [comment]
It's AppVeyor, not Travis and please revieww my patches.

**Pull request merged**
