### PR TITLE
Executables branch update (Simplification: use Arctan for the optimism S-curve bench 5544908)

### PR DESCRIPTION
**Pull request by double-beep**
See issue #174

### CODE REVIEW

**Comment by double-beep** [comment]
@Counterply, could you please write instead of "Executables", "*Name of the patch*" and the bench in the description?

**Comment by CounterPly** [comment]
Absolutely! Sorry, I wasn't aware that I pushed that to my repository rather than lantonov/asmFish. I'll correct it now and add a proper description. (I am not sure how to rename that commit from this PR, so I'll just copy it over manually. Thanks for bringing this to my attention, @double-beep)

**Comment by CounterPly** [comment]
Updated executables branch (for real this time).

**Comment by double-beep** [comment]
Ok, @Counterply thanks!

**Pull request closed without merging**
