### PR TITLE
Old time management

### PR DESCRIPTION
**Pull request by CounterPly**
Implemented Moha's suggestions and cleaned up formatting. PR should now also be mergeable with master.

Quick question for lantonov:

In your last speed test on Build Tester, was the "test" build based off of calign 64 or calign 16 in CheckTime.asm? Moha mentioned both were possible, so I was wondering if this made any statistically significant difference in speed?

### CODE REVIEW

**Comment by lantonov** [comment]
The last speed test was with calign 16. At the moment I have no access to my 64bit machine but intend to make a test with calign 64 (align 64 ?) this evening and then merge the best one.

**Comment by lantonov** [comment]
I don't know what is the difference between align and calign and if it makes sense to test both

**Comment by lantonov** [comment]
This is a comparison between master and versions with align 64 and calign 64. Because these are 3 comparables, ANOVA is used instead of t test. Differences are not significant at 95% level (ANOVA failed). The best is align 64 (marginally better than calign 16 (0.392% vs 0.395% slowdown) but with much lower SD (70,522 vs 102,195)). For comparison, I copied the previous tests below.
So, I will merge now and change to align 64.

Build Tester: 1.4.7.0
Windows 10 (Version 10.0, Build 0, 64-bit Edition)
Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
SafeMode: No 
Running In VM: No 
HyperThreading Enabled: No 
CPU Warmup: Yes
Command Line: bench 256 4 18 default depth
Tests per Build: 30
ANOVA: Failed
engine 1: master (b2e1185)
engine 2: align 64
engine 3: calign 64
master: best 5,889,748; worst 5,546,559; sd 72,804.7
align 64: best 5,863,220; worst 5,545,192; sd 70,522.6
calign 64: best 5,891,743; worst 5,536,631; sd 81,966.7
```
                Engine# (NPS)                     Speedup     Sp     Conf. 95%    S.S.
1  (5,748,364.9   ) ---> 2  (5,725,915.5   ) --->  0.392%  71,672.7     No        No 
1  (5,748,364.9   ) ---> 3  (5,716,657.3   ) --->  0.555%  77,521.2     No        No 
```

Engine 1: old_tm (original)
Engine 2: master (b2e1185)
30 speed tests per build
```
                Engine# (NPS)                     Speedup     Sp     Conf. 95%    S.S.
2  (5,723,766.9   ) ---> 1  (5,657,435.5   ) --->  1.172%  98,027.3     Yes       No 
```
So there is some slowdown of 1.2% which is significant at 95% conf level
Some more stats:
Best: 1 - 5,836,713 | 2 - 5,835,315
Worst: 1 - 5,299,695 | 2 - 5,577,962
Std Dev: 1 - 116,967.4 | 2 - 74,413.2 (the speed of the test build is more unstable)

Engine 1: old_tm (calign 16)
Engine 2: master (b2e1185)
30 speed tests per build
```
                Engine# (NPS)                     Speedup     Sp     Conf. 95%    S.S.
2  (5,748,243.7   ) ---> 1  (5,725,624.2   ) --->  0.395%  102,195.3    No        No 
```
The slowdown of 0.395% is not significant at 95% conf level
Some more stats:
Best: 1 - 5,905,078 | 2 - 5,874,690
Worst: 1 - 5,277,365 | 2 - 5,461,620
Std Dev: 1 - 120,217.6 | 2 - 80,221.5

**Comment by CounterPly** [comment]
Thanks, lantonov. Very interesting test results. 

With regard to your question, I believe calign is a macro defined in fasmg by the following:

```
macro calign n 
      align n*2 
end macro 
```

See https://board.flatassembler.net/topic.php?p=201192 for more details.

**Comment by lantonov** [comment]
Thanks for explaining. So calign 16 is the same as align 32

**Comment by CounterPly** [comment]
Yes, and calign 64 would be the same as align 128, which could help explain the destabilization we observe.

**Comment by lantonov** [comment]
I will make one last test with calign 32 (= align 64) to see how to modify the pull request (calign 64)

engine 1: master (b2e1185)
engine 2: calign 32
```
                Engine# (NPS)                     Speedup     Sp     Conf. 95%    S.S.
1  (5,740,281.6   ) ---> 2  (5,729,947.7   ) --->  0.180%  67,841.4     No        No 
```
master: best 5,922,225 worst 5,622,814 sd 75,691.6
calign 32: best 5,839,236 worst 5,629,409 sd 58,954.9
calign 32 is best so changing accordingly

**Comment by CounterPly** [comment]
Excellent -- that's a great SD. Good job with these tests. I'm wondering if it would be worth going back through the code with a fine-toothed comb and possibly upgrading to additional calign 32's.

**Comment by lantonov** [comment]
Sure, I can make as many tests as needed

**Comment by tthsqe12** [comment]
No no no. There is no such thing as a macro defined inside fasmg. calign is defined in https://github.com/lantonov/asmFish/blob/master/x86/fasm1macros.asm
The two parameter form also allows aligning an arbitrary target.

**Pull request merged**
