### PR TITLE
Update flat assembler g to version i8imp

### PR DESCRIPTION
**Pull request by double-beep**
This is the latest release of fasmg from July 13, 2018. Program assembly supported for various architectures including x86, x64, 8052, AVR, and Java Virtual Machine.

https://flatassembler.net/download.php

No functional change.

### CODE REVIEW

**Comment by CounterPly** [comment]
Thanks, I'll commit this with the next functional change.

**Comment by double-beep** [comment]
There is a newer version of fasmg. The 2 versions (g.i8imp and g.i88rw) made the compilation ~100sec faster!?

**Comment by double-beep** [comment]
But the newest causes problems: make.bat finishes the assemble after the `move` command!

**Comment by double-beep** [comment]
But the newest causes problems: make.bat finishes the assemble after the move command! Anyway, comparing https://ci.appveyor.com/project/double-beep/asmfish-i5x4k/build/3.0.500 (latest fasmg) and https://ci.appveyor.com/project/double-beep/asmfish-i5x4k/build/3.0.497 ??

**Pull request closed without merging**
