### PR TITLE
[x86] Penalty for bad bishop with blocked central files

### PR DESCRIPTION
**Pull request by double-beep**
bench: 5364190
official-stockfish/stockfish@57acdad

### CODE REVIEW

**Comment by CounterPly** [comment]
Yes, I am still working on the arm version, which is why I haven't committed it yet. Thanks for staying up to date on its progress though. I will commit both of them together later today.

**Comment by CounterPly** [comment]
(Also, I think there may be some opportunity to tighten this code and save instructions. I wrote it somewhat late at night, so I'll take a fresh look at it again shortly.)

**Comment by double-beep** [comment]
Yes, ok.

**Comment by double-beep** [comment]
Have asmFish and armFish's benches differences?

**Comment by CounterPly** [comment]
> You are completely right. Any idea for:
set bench = %stockfish's bench%
if %asmFish's bench% ≠ %stockfish's bench%
build failure
end if

I'll think about it. One idea would be to automate Moha's [checker.py](https://github.com/lantonov/asmFish/blob/master/x86/checker.py) script to automatically perform a deep-bench comparison between SF and asmFish. This would be particularly plausible if AppVeyor's computers come with Python pre-installed. If you feel up to it, I think that would be worthwhile to take a look at.

**Comment by CounterPly** [comment]
> Have asmFish and armFish's benches differences?

I got them to be identical once again (finally).

**Comment by double-beep** [comment]
Yes, I think using checker.py may help, but I don't know python.

**Pull request closed without merging**
